service: lambda-fitnesse

provider:
  name: aws
  runtime: nodejs4.3

  stage: dev

  iamRoleStatements:
      - Effect: "Allow"
        Action: "logs:*"
        Resource: "*"
      - Effect: "Allow"
        Action: "lambda:*"
        Resource: "*"

custom:
  writeEnvVars:
    API: ${opt:API}

functions:
  lambdaFitnesse:
    handler: handler.lambdaFitnesse

plugins:
  - serverless-run-function-plugin
  - serverless-plugin-write-env-vars
